#http://guides.cocoapods.org/syntax/podfile.html#project
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# git clone https://gitclub.cn/CocoaPods/Specs.git ~/.cocoapods/repos/master

$LOAD_PATH << '.'
require 'PodStatic'

plugin 'cocoapods-binary'


install! 'cocoapods', :deterministic_uuids => false


# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'


# 设置binary缓存
enable_binary_cache(true)
# dev pod是否添加到cache
# enable_local_binary_cache(true)
# 设置同步服务器，rsync形式，需要设置目标机器密码: export RSYNC_PASSWORD=xxx
set_rsync_server_url("rsync_backup@192.168.0.201::out")
# 设置同步文件夹
#set_rsync_path("/Users/yans/Desktop/ftp")

target 'testpodFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
#    use_frameworks!

    # 所有都进行二进制编译，如果要忽略某个后面添加‘, :binary => false’
    all_binary!

    # 允许dev pod
    all_local_binary!
    
    # 保留源码，可能工程文件会很大
    # keep_source_for_prebuilt!
    
    # 开放framework 的private header
    # public_headers_for_prebuilt!
    
    pod 'FTPopOverMenu', :path => './FTPopOverMenu', :binary => true
#    pod 'MPNotificationView'
#    pod 'Masonry', :binary => true


#    pod 'YSBeeFramework', :path => './YSBeeFramework', :binary => true
#    pod 'YSBeeFramework', :git => 'http://192.168.3.31/TY_iOS_Librarys/YSBeeFramework.git', :tag => '1.3.1'#, branch: 'core-0.6.0'

#    pod 'YSTableView/MouseHeader', :git => 'http://192.168.3.31/TY_iOS_Librarys/YSTableView.git', :tag => '0.2.3'# 老鼠 MouseHeader

#    pod 'TestEngineService', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7', :binary => false

#    pod 'TestEngineService/Core', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7'
#    pod 'TestEngineService/ST', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7'
#    pod 'TestEngineService/CV', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7'


    
#    pod 'Bugly'
#    pod 'PDBotKit' #智能客服

end


# gem build ./cocoapods-binary/cocoapods-binary && sudo gem install ./cocoapods-binary/cocoapods-binary && rm -R -f ./Pods && clear && pod install --verbose

# cd ./cocoapods-binary && gem build cocoapods-binary && sudo gem install cocoapods-binary && cd .. && rm -R -f ./Pods && clear && pod install --verbose

# clear && gem build cocoapods-binary && sudo gem install cocoapods-binary
# rm -R -f ./Pods && clear && pod install --verbose
# rm -R -f ./Pods && clear && pod update --verbose


#https://www.rubydoc.info/github/CocoaPods/Core/master/Pod/Specification/Consumer
#https://www.runoob.com/ruby/ruby-command-line-options.html
#https://docs.fission.io/docs/spec/podspec/
#https://rubydoc.info/gems/cocoapods/Pod/Sandbox/HeadersStore
#https://github.com/CocoaPods/CocoaPods/blob/7b246db45e414ef05a38d7ff25a9e453fce12ffb/lib/cocoapods/sandbox/file_accessor.rb




post_install do |installer|

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.3'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end

    PodStatic.enableStaticLib(false)
    PodStatic.forceBuild(false)
    PodStatic.simulatorSupport(true)
    PodStatic.autoValidArchs(true)
    # 和use_frameworks!对应起来
    # PodStatic.useFrameworks(false)

                            
    PodStatic.run(installer, [
                  'MPNotificationView',
                  'FTPopOverMenu',
                  ])
end

