#http://guides.cocoapods.org/syntax/podfile.html#project
source 'http://192.168.3.31/TY_iOS_Librarys/tyspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
# source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
# git clone https://gitclub.cn/CocoaPods/Specs.git ~/.cocoapods/repos/master

$LOAD_PATH << '.'
require 'PodStatic'

plugin 'cocoapods-binary'


install! 'cocoapods', :deterministic_uuids => false


# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'


# 设置binary缓存
enable_binary_cache(true)
# dev pod是否添加到cache
# enable_local_binary_cache(true)
# 设置同步服务器，rsync形式，需要设置目标机器密码: export RSYNC_PASSWORD=xxx
#set_rsync_server_url("rsync_backup@192.168.0.201::out")
# 设置同步文件夹
set_rsync_path("/Users/yans/Desktop/ftp")
set_clean_build_dir(false)
# 是否只缓存 .a 文件不包含 .h 以及resource文件
set_only_store_lib_file(false)
set_binary_white_list([
#                      'YSNSObjectSafe',
#                      'NullSafe',
#                      'DACircularProgress',
#                      'FMDB',
#                      'Reachability',
#                      'TouchXML',
#                      'YSTableView'
                      ])
# 开启调试日志
set_verbose_log(true)

# 开启subspec 的md5文件名区分
set_md5_file_name(false)


abstract_target 'base' do
    # 所有都进行二进制编译，如果要忽略某个后面添加‘, :binary => false’
    all_binary!
    
    
    pod 'YSTableView',   '= 0.2.3', :subspecs => ['EyemanHeader']

    
    
    pod 'UMCCommon'
    #pod 'UMCSecurityPlugins'
    #pod 'UMCAnalytics'
    
    pod 'UMCShare/Core'
    # 集成QQ/QZone/TIM(完整版7.6M)
    #pod 'UMCShare/Social/QQ'
    # 集成QQ/QZone/TIM(精简版0.5M)
    pod 'UMCShare/Social/ReducedQQ'
    # 集成新浪微博(完整版25.3M)
    #pod 'UMCShare/Social/Sina'
    # 集成新浪微博(精简版1M)
    pod 'UMCShare/Social/ReducedSina'
    # 集成微信(完整版14.4M)
    #    pod 'UMCShare/Social/WeChat'
    # 集成微信(精简版0.2M) 如果要用到支付需要手动集成支付
    #    pod 'UMCShare/Social/ReducedWeChat'
#    pod 'UMCShare/Social/WeChat'
    #    pod 'WechatOpenSDK'

    

    target 'testpodFramework' do
      # Comment the next line if you don't want to use dynamic frameworks
    #    use_frameworks!

    pod 'UMCShare/Core'


        # 允许dev pod
        all_local_binary!
        
        # 保留源码，可能工程文件会很大
         keep_source_for_prebuilt!
        
        # 开放framework 的private header
        # public_headers_for_prebuilt!
        
    #    pod 'FTPopOverMenu', :path => './FTPopOverMenu', :binary => true, :project_name => 'Dev'
    #    pod 'MPNotificationView', :binary => true
    #    pod 'Masonry', :project_name => 'Github', :binary => false


    #    pod 'YSBeeFramework', :path => './YSBeeFramework', :binary => true
    #    pod 'YSBeeFramework', :git => 'http://192.168.3.31/TY_iOS_Librarys/YSBeeFramework.git', :tag => '1.3.1'#, branch: 'core-0.6.0'

    #    pod 'YSTableView/MouseHeader', :git => 'http://192.168.3.31/TY_iOS_Librarys/YSTableView.git', :tag => '0.2.3'# 老鼠 MouseHeader

    #    pod 'TestEngineService', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7', :binary => false

    #    pod 'TestEngineService/Core', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7'
    #    pod 'TestEngineService/ST', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7'
    #    pod 'TestEngineService/CV', :git => 'https://bitbucket.org/tytto/testengineservice.git', :tag => '0.4.7'


    #     pod 'YSNSObjectSafe', :git => 'http://192.168.3.31/TY_iOS_Librarys/YSNSObjectSafe.git', :tag => '1.1.0', :binary => true
         
    #     pod 'YSNSObjectSafe', :git => 'https://bitbucket.org/tytto/ysnsobjectsafe.git', :tag => '1.1.0', :binary => true

         
    #     pod 'YSTableView', '= 0.2.3', :subspecs => ['EyemanHeader', 'IndicatorFooter']
    #     pod 'YSBeeFramework', '= 6.1.3'#, branch: 'core-0.6.0'


#        pod 'YSTableView'#,  :subspecs => ['EyemanHeader']

         

    #    pod 'Bugly', :project_name => 'Framework'
    #    pod 'PDBotKit', :project_name => 'Framework'
    #    pod 'YSWCDBService', :git => 'http://192.168.3.31/TY_iOS_Librarys/YSWCDBService.git', :tag => '1.0.6'

    #    pod 'WCDBOptimizedSQLCipher'
    #    pod 'SQLiteRepairKit'
    #    pod 'WCDB'
    end
    
    target 'test2' do

    end

end

# gem build ./cocoapods-binary/cocoapods-binary && sudo gem install ./cocoapods-binary/cocoapods-binary && rm -R -f ./Pods && clear && pod install --verbose

# cd ./cocoapods-binary && gem build cocoapods-binary && sudo gem install cocoapods-binary && cd .. && rm -R -f ./Pods && clear && pod install --verbose

# clear && sudo gem build cocoapods-binary && sudo gem install cocoapods-binary
# rm -R -f ./Pods && clear && pod install --verbose
# rm -R -f ./Pods && clear && pod update --verbose

# 安装
# sudo gem install cocoapods-binary-0.4.4.gem

#https://www.rubydoc.info/github/CocoaPods/Core/master/Pod/Specification/Consumer
#https://www.runoob.com/ruby/ruby-command-line-options.html
#https://docs.fission.io/docs/spec/podspec/
#https://rubydoc.info/gems/cocoapods/Pod/Sandbox/HeadersStore
#https://github.com/CocoaPods/CocoaPods/blob/7b246db45e414ef05a38d7ff25a9e453fce12ffb/lib/cocoapods/sandbox/file_accessor.rb


post_install do |installer|
    
    
    # PodStatic
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.3'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end

    PodStatic.enableStaticLib(false)
    PodStatic.forceBuild(false)
    PodStatic.simulatorSupport(true)
    PodStatic.autoValidArchs(true)
    # 和use_frameworks!对应起来
    # PodStatic.useFrameworks(false)

                            
    PodStatic.run(installer, [
                  'MPNotificationView',
                  'FTPopOverMenu',
                  ])
end

