#http://guides.cocoapods.org/syntax/podfile.html#project
#source 'https://github.com/CocoaPods/Specs.git'
# git clone https://gitclub.cn/CocoaPods/Specs.git ~/.cocoapods/repos/master


$LOAD_PATH << '../'
require 'PodStatic'


platform :ios, '8.0'
plugin 'cocoapods-binary'


install! 'cocoapods', :deterministic_uuids => false


target 'demo' do


	#use_frameworks!
	all_binary!

	# 保留源码
	keep_source_code_for_prebuilt_frameworks!


	pod 'Masonry'
	pod 'MPNotificationView'
  pod 'FTPopOverMenu'

end



# gem build cocoapods-binary && sudo gem install cocoapods-binary

post_install do |installer|

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.3'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
        end
    end

    PodStatic.enableStaticLib(false)
    PodStatic.forceBuild(false)
    PodStatic.simulatorSupport(true)
    PodStatic.autoValidArchs(true)
    # 和use_frameworks!对应起来
    # PodStatic.useFrameworks(false)

                            
    PodStatic.run(installer, [
                  'MPNotificationView',
                  'FTPopOverMenu',
                  ])
end

